on: push

env:
  CARGO_TERM_COLOR: always

name: Development Build
jobs:
  release:
    name: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: linux-i686
            runner: ubuntu-latest
            target: i686-unknown-linux-gnu
          - name: linux-arm64
            runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - name: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Rust Dependency Cache
        uses: Swatinem/rust-cache@master

      - name: Build
        uses: clechasseur/rs-cargo@v2
        with:
          command: build
          args: --release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.target }}
          path: |
            target/release/bmap-server
